### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by Rik44444** [jlu5/bookmarksync#11]
Hi all,
I'm using Tuxedo OS (Ubuntu derivative using KDE) and would love to use this app.
How do you recommend I install this on Ubuntu? Is there a repo or Flatpak that I can use? 
Rik

**Comment by jlu5** [comment]
If there's no package for your OS, the only option is to build from source currently.

 I may look into Flatpak at some point though it's not a packaging format I'm familiar with yet.

**Comment by Rik44444** [comment]
OK thanks. Might be worthwhile to create a package for Ubuntu at some point, given how many users there are on Ubuntu! I've never built from source, is it as simple as your instruction suggests - can I just enter those lines in the terminal and then I get a binary that will work? Or do i need some dev knowledge (which i dont have)

**Comment by jlu5** [comment]
>  Might be worthwhile to create a package for Ubuntu at some point, given how many users there are on Ubuntu!

Sure, but I like testing/vetting package updates manually, especially for things that have a GUI, and it's hard for me to spend that much time on an OS I don't personally use.

That said, I'm a Debian developer and it's possible to push bookmarksync into the Debian & Ubuntu repos directly, but I only want to do that if there's enough demand to justify the maintenance effort.

> I've never built from source, is it as simple as your instruction suggests - can I just enter those lines in the terminal and then I get a binary that will work? 

More or less, yeah. Dev knowledge is mostly helpful to debug any issues that may pop up during the process, but you can paste any errors you get if you run into them.

**Comment by Rik44444** [comment]
Cool that worked thanks!
