### ISSUE TITLE
Feature request: add option to sync daily

### ISSUE THREAD

**Issue by Rik44444** [jlu5/bookmarksync#12]
Feature request to add an ability to sync daily 

Possible UIs:

E.g. add next to each "Copy to the other side" button an extra button called "Copy daily to the other side". Of the three buttons "Copy daily to the other side", max 1 should be selectable at the same time. 

E.g. 2 add a separate dropdown on top with 4 options: 
1. sync none daily
2. sync GTK+ to rest daily
3. sync KDE to rest daily
4. sync QT local to rest daily

**Comment by jlu5** [comment]
Bookmarksync has a [CLI mode](https://github.com/jlu5/bookmarksync#cli-mode), perhaps you can try adding that to a [crontab](https://www.adminschoice.com/crontab-quick-reference)?

Using the system task scheduler is infinitely more flexible than hardcoding this into the program itself. (And architecturally this would require a lot more work, because bookmarksync doesn't stay running after you close it)

**Comment by Rik44444** [comment]
OK I will try :)!

**Comment by Rik44444** [comment]
Two follow up questions:

1. Your Readme writes: "As of v0.3.0 there is support for running sync from the command line: $ bookmarksync --sync-from {gtk,kde,qt}."  --> does this mean that the command for syncing GTK to the rest is: 
`$ bookmarksync --sync-from {gtk}` ?

2. My system says "bookmarksync: command not found" when I perform this operation. Is that because I built Bookmarksync from source?

**Comment by jlu5** [comment]
> Your Readme writes: "As of v0.3.0 there is support for running sync from the command line: $ bookmarksync --sync-from {gtk,kde,qt}." --> does this mean that the command for syncing GTK to the rest is:
$ bookmarksync --sync-from {gtk} ?

Omit the braces, `bookmarksync --sync-from gtk`

> My system says "bookmarksync: command not found" when I perform this operation. Is that because I built Bookmarksync from source?

Specify the full path to the bookmarksync binary if it's not in your system [PATH](https://www.digitalocean.com/community/tutorials/how-to-view-and-update-the-linux-path-environment-variable)
